### ISSUE TITLE
Question: Controller HW & SW enviroment

### ISSUE THREAD

**Issue by rolox19** [beckdac/SCARA#1]
Hi, this SCARA arm looks very good, I like   test it.
What is the controller hardware (Raspberry Pi?) and what kind of developing enviroment need for build the controller software?

**Comment by beckdac** [comment]
Yes, it is Raspberry Pi.  The controller code is written in C.  There is more documentation and discussion on the thingiverse remix someone made for customizer: 
http://www.thingiverse.com/thing:1353302
